package com.scaler.Uber;

import java.util.PriorityQueue;
import java.util.UUID;

public class Driver {
    final private String driverId;
    private String driverName;
    private String phone;
    private boolean isOnline;
    public static int totalNoOfDrivers;

    public  Driver() {
        this.driverId = UUID.randomUUID().toString();
    }

    public Driver(String driverId, String driverName, String phone, boolean isOnline) {
        this.driverId = driverId;
        this.driverName = driverName;
        this.phone = phone;
        this.isOnline = isOnline;
    }
    public static String autoGenerateDriverId(){
        return UUID.randomUUID().toString();
    }
    public Driver(String driverName, String phone){
//        this.driverId = "";//AutoGenerated or Internally; UUID.generate();
//        this.driverName = driverName;
//        this.phone = phone;
//        this.isOnline = false;
        this(autoGenerateDriverId(), driverName, phone, false); // Should always be the first line
    }
    public Driver(String phone){
//        System.out.println("Creating Driver");
        this( "Default", phone); // Should be the first line
        this.setOnline();
    }

    public void setOnline() {
        this.isOnline = true;
    }
    public String getMaskedPhone() {
        String maskedPhone = "***" + phone; // Logic for generating a masked phone no
        return maskedPhone;
    }

//    public void setDriverId(String driverId) {
//        this.driverId = driverId;
//    }
}
// When we create an object - To create a new driver, or to fetch data of an existing driver
// Driver d= new Driver(,,,) -> d.save()[Gets saved in DB]
// Array[] = DriverTable.fetchQuery; -> Driver d = new Driver(arr[1], arr[2]) // Will be done internally by ORMs
// DRY - Don't repeat yourself

// Final :
//final on variable → assigned once, never changed
//final on method   → cannot be overridden by a subclass // After inheritance
//final on class    → cannot be subclassed at all // After INHERITANCE